/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * Site layout helpers — the shared page chrome (document head, global nav,
 * footer) for the server-rendered site: explorer, ZNAM names, store, blog,
 * and any future /zcode route family. Pure header-only emitters over caller
 * buffers, following the explorer_emit_nav() pattern in
 * controllers/explorer_internal.h.
 *
 * The stylesheet is NOT here: it is the compiled `site_css` symbol in
 * views/site_css.h (generated by `make site-css` from
 * app/views/src/site.css). Pages either link it as /explorer/style.css
 * (explorer) or inline it in a <style> block via site_emit_head's css
 * parameter (names/store/blog — one round trip over the onion, whose
 * response buffer is 64 KiB).
 *
 * Contract for a new page family: open with site_emit_head(), emit
 * site_emit_global_nav() with the family's active id, mark the main content
 * with <main id='content'>, close with site_emit_footer(). Use the token
 * classes from site.css (.card/.grid/table/.pill/.btn/...) rather than
 * inventing page-local styles. */

#ifndef ZCL_VIEWS_SITE_LAYOUT_H
#define ZCL_VIEWS_SITE_LAYOUT_H

#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>

/* Same append-with-truncation-guard semantics as APPEND in
 * controllers/explorer_internal.h; separate name so both headers can be
 * included together. */
#define SITE_APPEND(off, buf, max, ...) do { \
    if ((off) < (max)) { \
        size_t _rem = (max) - (off); \
        int _n = snprintf((char *)(buf) + (off), _rem, __VA_ARGS__); \
        if (_n > 0) { \
            (off) += ((size_t)_n < _rem) ? (size_t)_n : _rem - 1; \
        } \
    } \
} while (0)

/* Global site nav — the one bar that unifies every route family. `active`
 * is one of "explorer", "names", "store", "blog", "directory" (the link
 * gets class='active'), or NULL to highlight nothing. Keep the link set
 * here and in SITE_GLOBAL_NAV below in lockstep. */
static inline size_t site_emit_global_nav(char *buf, size_t max,
                                          const char *active)
{
    static const struct { const char *href; const char *label; const char *id; }
        links[] = {
        { "/explorer",  "Explorer",  "explorer"  },
        { "/names",     "Names",     "names"     },
        { "/store",     "Store",     "store"     },
        { "/blog",      "Blog",      "blog"      },
        { "/directory", "Directory", "directory" },
    };
    size_t off = 0;
    SITE_APPEND(off, buf, max,
        "<header class='site-top'>"
        "<a class='brand' href='/'>"
        "<span class='glyph' aria-hidden='true'>Z</span>"
        "<span>ZClassic23</span></a>"
        "<nav aria-label='Site'>");
    for (size_t i = 0; i < sizeof(links) / sizeof(links[0]); i++) {
        bool act = active && strcmp(active, links[i].id) == 0;
        SITE_APPEND(off, buf, max, "<a href='%s'%s>%s</a>",
                    links[i].href, act ? " class='active'" : "",
                    links[i].label);
    }
    SITE_APPEND(off, buf, max, "</nav></header>");
    return off;
}

/* Literal twin of site_emit_global_nav(active=NULL) for one-shot snprintf
 * format strings (legacy explorer error pages). */
#define SITE_GLOBAL_NAV \
    "<header class='site-top'>" \
    "<a class='brand' href='/'>" \
    "<span class='glyph' aria-hidden='true'>Z</span>" \
    "<span>ZClassic23</span></a>" \
    "<nav aria-label='Site'>" \
    "<a href='/explorer'>Explorer</a>" \
    "<a href='/names'>Names</a>" \
    "<a href='/store'>Store</a>" \
    "<a href='/blog'>Blog</a>" \
    "<a href='/directory'>Directory</a>" \
    "</nav></header>"

/* Document open: doctype through <body>. When `css` is non-NULL it is
 * inlined in a <style> block (single-round-trip pages over the onion);
 * when NULL the page links the shared external stylesheet the explorer
 * serves at /explorer/style.css. `body_class` may be NULL or "measure"
 * (narrow reading column for prose/app pages). Emits a skip link targeting
 * #content — mark the main content container with id='content'. */
static inline size_t site_emit_head(char *buf, size_t max, const char *title,
                                    const char *css, const char *body_class)
{
    size_t off = 0;
    SITE_APPEND(off, buf, max,
        "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>%s</title>",
        (title && title[0]) ? title : "ZClassic23");
    if (css)
        SITE_APPEND(off, buf, max, "<style>%s</style>", css);
    else
        SITE_APPEND(off, buf, max,
            "<link rel='stylesheet' href='/explorer/style.css'>");
    SITE_APPEND(off, buf, max, "</head><body");
    if (body_class && body_class[0])
        SITE_APPEND(off, buf, max, " class='%s'", body_class);
    SITE_APPEND(off, buf, max,
        "><a class='skip' href='#content'>Skip to content</a>");
    return off;
}

/* Document close: site footer + </body></html>. */
static inline size_t site_emit_footer(char *buf, size_t max, const char *text)
{
    size_t off = 0;
    SITE_APPEND(off, buf, max, "<footer>%s</footer></body></html>",
        (text && text[0]) ? text
                          : "ZClassic23 &mdash; one binary, one onion, one stack");
    return off;
}

#endif /* ZCL_VIEWS_SITE_LAYOUT_H */
